import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.join(__dirname, '..', '.env') });

import mongoose from 'mongoose';
import connectDB from '../config/db.js';
import Product from '../models/Product.js';

// All images sourced from cdn.dummyjson.com — guaranteed to load, professional product photography
const D = 'https://cdn.dummyjson.com/product-images';

const seedProducts = [
  // ===== ELECTRONICS (7) =====
  {
    name: 'Professional Studio Camera Pedestal',
    price: 499.0,
    originalPrice: 599.0,
    images: [
      `${D}/mobile-accessories/tv-studio-camera-pedestal/1.webp`,
    ],
    description: 'Professional-grade camera support system for smooth and precise camera movements in a studio setting.',
    category: 'Electronics',
    stock: 25,
    rating: 4.5,
    reviewCount: 154,
    isFeatured: true,
    tags: ['camera', 'studio', 'photography', 'tripod'],
    brand: 'ProVision',
    features: ['Stable', 'Adjustable', 'Metallic'],
    condition: 'Brand new',
  },
  {
    name: 'Selfie Ring Light with Smartphone Holder',
    price: 45.0,
    originalPrice: 60.0,
    images: [
      `${D}/mobile-accessories/selfie-lamp-with-iphone/1.webp`,
    ],
    description: 'Dimmable LED ring light with flexible phone holder, perfect for content creators and live streaming.',
    category: 'Electronics',
    stock: 18,
    rating: 4.8,
    reviewCount: 154,
    isFeatured: true,
    tags: ['lighting', 'selfie', 'ring light', 'content'],
    brand: 'SnapTech',
    features: ['Dimmable', 'Portable'],
    condition: 'Brand new',
  },
  {
    name: 'Samsung Galaxy S24 Ultra 256GB',
    price: 1199.0,
    originalPrice: 1399.0,
    images: [
      `${D}/smartphones/samsung-galaxy-s10/1.webp`,
      `${D}/smartphones/samsung-galaxy-s10/2.webp`,
      `${D}/smartphones/samsung-galaxy-s10/3.webp`,
    ],
    description: 'Flagship smartphone with S Pen, titanium frame, and advanced AI features for the ultimate mobile experience.',
    category: 'Electronics',
    stock: 12,
    rating: 5.0,
    reviewCount: 412,
    isFeatured: true,
    tags: ['samsung', 'galaxy', 'smartphone', '5g'],
    brand: 'Samsung',
    features: ['8GB Ram', 'Super power', 'Large Memory', 'Metallic'],
    condition: 'Brand new',
  },
  {
    name: 'Apple AirPods Pro 2nd Generation',
    price: 249.0,
    originalPrice: null,
    images: [
      `${D}/mobile-accessories/apple-airpods/1.webp`,
      `${D}/mobile-accessories/apple-airpods/2.webp`,
      `${D}/mobile-accessories/apple-airpods/3.webp`,
    ],
    description: 'Active noise cancellation, adaptive transparency, and personalized spatial audio with dynamic head tracking.',
    category: 'Electronics',
    stock: 40,
    rating: 4.7,
    reviewCount: 289,
    isFeatured: false,
    tags: ['apple', 'airpods', 'earbuds', 'wireless'],
    brand: 'Apple',
    features: ['Metallic'],
    condition: 'Brand new',
  },
  {
    name: 'Huawei MateBook D15 Laptop',
    price: 699.0,
    originalPrice: 899.0,
    images: [
      `${D}/laptops/huawei-matebook-x-pro/1.webp`,
      `${D}/laptops/huawei-matebook-x-pro/2.webp`,
      `${D}/laptops/huawei-matebook-x-pro/3.webp`,
    ],
    description: 'Ultra-slim 15.6 inch laptop with full-view display, fast charging, and multi-screen collaboration.',
    category: 'Electronics',
    stock: 8,
    rating: 4.3,
    reviewCount: 97,
    isFeatured: false,
    tags: ['huawei', 'laptop', 'ultrabook', 'productivity'],
    brand: 'Huawei',
    features: ['8GB Ram', 'Large Memory', 'Super power', 'Metallic'],
    condition: 'Refurbished',
  },
  {
    name: 'Xiaomi Redmi 8 Original',
    price: 32.0,
    originalPrice: 40.0,
    images: [
      `${D}/smartphones/oppo-a57/1.webp`,
      `${D}/smartphones/oppo-a57/2.webp`,
    ],
    description: 'Budget-friendly smartphone with 6.22" display, dual camera, and 5000mAh long-lasting battery.',
    category: 'Electronics',
    stock: 50,
    rating: 4.2,
    reviewCount: 89,
    isFeatured: false,
    tags: ['smartphone', 'xiaomi', 'redmi', 'mobile'],
    brand: 'Xiaomi',
    features: ['8GB Ram', 'Plastic cover'],
    condition: 'Brand new',
  },
  {
    name: 'Lenovo Gaming Headset with Mic',
    price: 8.99,
    originalPrice: null,
    images: [
      `${D}/mobile-accessories/apple-airpods-max-silver/1.webp`,
    ],
    description: 'Gaming headset with surround sound, noise-canceling microphone, and comfortable ear cushions for long gaming sessions.',
    category: 'Electronics',
    stock: 60,
    rating: 4.4,
    reviewCount: 198,
    isFeatured: false,
    tags: ['headset', 'gaming', 'microphone', 'audio'],
    brand: 'Lenovo',
    features: ['Plastic cover'],
    condition: 'Brand new',
  },

  // ===== CLOTHING (5) =====
  {
    name: 'Men Blazers Sets Elegant Formal',
    price: 99.5,
    originalPrice: null,
    images: [
      `${D}/mens-shirts/men-check-shirt/1.webp`,
      `${D}/mens-shirts/men-check-shirt/2.webp`,
    ],
    description: 'Elegant formal blazer set for men, perfect for business meetings and special occasions.',
    category: 'Clothing',
    stock: 15,
    rating: 4.1,
    reviewCount: 45,
    isFeatured: false,
    tags: ['blazer', 'formal', 'men', 'suit'],
    brand: 'Unbranded',
    features: [],
    condition: 'Brand new',
  },
  {
    name: 'T-shirts with multiple colors, for men',
    price: 10.3,
    originalPrice: null,
    images: [
      `${D}/mens-shirts/gigabyte-aorus-men-tshirt/1.webp`,
      `${D}/mens-shirts/gigabyte-aorus-men-tshirt/2.webp`,
      `${D}/mens-shirts/gigabyte-aorus-men-tshirt/3.webp`,
    ],
    description: 'Comfortable cotton t-shirt available in multiple vibrant colors. Breathable fabric for everyday wear.',
    category: 'Clothing',
    stock: 100,
    rating: 3.0,
    reviewCount: 12,
    isFeatured: false,
    tags: ['t-shirt', 'cotton', 'casual', 'men'],
    brand: 'Unbranded',
    features: [],
    condition: 'Brand new',
  },
  {
    name: 'Jeans shorts for men blue color',
    price: 10.3,
    originalPrice: null,
    images: [
      `${D}/mens-shirts/man-short-sleeve-shirt/1.webp`,
      `${D}/mens-shirts/man-short-sleeve-shirt/2.webp`,
    ],
    description: 'Classic blue jeans shorts, lightweight and comfortable for everyday wear.',
    category: 'Clothing',
    stock: 40,
    rating: 2.5,
    reviewCount: 8,
    isFeatured: false,
    tags: ['jeans', 'shorts', 'blue', 'men'],
    brand: 'Unbranded',
    features: [],
    condition: 'Old items',
  },
  {
    name: 'Brown winter coat medium size',
    price: 12.5,
    originalPrice: null,
    images: [
      `${D}/mens-shirts/man-plaid-shirt/1.webp`,
      `${D}/mens-shirts/man-plaid-shirt/2.webp`,
    ],
    description: 'Warm brown winter coat with soft inner lining. Medium size fits most body types.',
    category: 'Clothing',
    stock: 20,
    rating: 4.6,
    reviewCount: 56,
    isFeatured: true,
    tags: ['coat', 'winter', 'brown', 'warm'],
    brand: 'Unbranded',
    features: [],
    condition: 'Brand new',
  },
  {
    name: "Women's Summer Dress Floral Print",
    price: 35.0,
    originalPrice: 50.0,
    images: [
      `${D}/mens-shirts/blue-&-black-check-shirt/1.webp`,
      `${D}/mens-shirts/blue-&-black-check-shirt/2.webp`,
    ],
    description: 'Beautiful floral print summer dress, lightweight and breathable fabric perfect for warm weather.',
    category: 'Clothing',
    stock: 30,
    rating: 4.3,
    reviewCount: 67,
    isFeatured: false,
    tags: ['dress', 'women', 'summer', 'floral'],
    brand: 'Unbranded',
    features: [],
    condition: 'Brand new',
  },

  // ===== ACCESSORIES (5) =====
  {
    name: 'Apple Watch Series Space Gray',
    price: 199.0,
    originalPrice: 250.0,
    images: [
      `${D}/mobile-accessories/apple-watch-series-4-gold/1.webp`,
      `${D}/mobile-accessories/apple-watch-series-4-gold/2.webp`,
      `${D}/mobile-accessories/apple-watch-series-4-gold/3.webp`,
    ],
    description: 'Smartwatch with health monitoring, fitness tracking, and seamless Apple ecosystem integration.',
    category: 'Accessories',
    stock: 30,
    rating: 4.9,
    reviewCount: 320,
    isFeatured: true,
    tags: ['apple', 'watch', 'smartwatch', 'wearable'],
    brand: 'Apple',
    features: ['Metallic', 'Super power'],
    condition: 'Brand new',
  },
  {
    name: 'Jeans bag for travel for men',
    price: 34.0,
    originalPrice: null,
    images: [
      `${D}/kitchen-accessories/lunch-box/1.webp`,
    ],
    description: 'Durable jeans travel bag with multiple compartments and reinforced stitching.',
    category: 'Accessories',
    stock: 35,
    rating: 4.7,
    reviewCount: 112,
    isFeatured: false,
    tags: ['bag', 'travel', 'jeans', 'durable'],
    brand: 'Unbranded',
    features: [],
    condition: 'Brand new',
  },
  {
    name: 'Leather wallet premium quality',
    price: 99.0,
    originalPrice: null,
    images: [
      `${D}/mens-watches/brown-leather-belt-watch/1.webp`,
      `${D}/mens-watches/brown-leather-belt-watch/2.webp`,
    ],
    description: 'Premium genuine leather wallet with RFID protection and multiple card slots.',
    category: 'Accessories',
    stock: 45,
    rating: 4.9,
    reviewCount: 230,
    isFeatured: true,
    tags: ['wallet', 'leather', 'premium', 'accessories'],
    brand: 'Unbranded',
    features: ['Metallic'],
    condition: 'Brand new',
  },
  {
    name: 'Pocco Smartwatch silver color modern',
    price: 10.3,
    originalPrice: null,
    images: [
      `${D}/mens-watches/rolex-datejust/1.webp`,
      `${D}/mens-watches/rolex-datejust/2.webp`,
    ],
    description: 'Modern silver smartwatch with health tracking, notifications, and long battery life.',
    category: 'Accessories',
    stock: 22,
    rating: 4.3,
    reviewCount: 67,
    isFeatured: false,
    tags: ['smartwatch', 'silver', 'modern', 'wearable'],
    brand: 'Pocco',
    features: ['Metallic', 'Plastic cover'],
    condition: 'Brand new',
  },
  {
    name: 'Pocco Smart Band 7 Fitness Tracker',
    price: 29.0,
    originalPrice: 39.0,
    images: [
      `${D}/mens-watches/longines-master-collection/1.webp`,
      `${D}/mens-watches/longines-master-collection/2.webp`,
    ],
    description: 'Lightweight fitness tracker with heart rate monitor, sleep tracking, and 14-day battery life.',
    category: 'Accessories',
    stock: 55,
    rating: 3.8,
    reviewCount: 42,
    isFeatured: false,
    tags: ['fitness', 'tracker', 'band', 'health'],
    brand: 'Pocco',
    features: ['Plastic cover'],
    condition: 'Brand new',
  },

  // ===== HOME & GARDEN (5) =====
  {
    name: 'Smart LED Desk Lamp Adjustable',
    price: 28.0,
    originalPrice: null,
    images: [
      `${D}/home-decoration/table-lamp/1.webp`,
    ],
    description: 'Adjustable LED desk lamp with multiple brightness levels and color temperatures for optimal reading.',
    category: 'Home & Garden',
    stock: 33,
    rating: 4.5,
    reviewCount: 78,
    isFeatured: false,
    tags: ['lamp', 'led', 'desk', 'smart'],
    brand: 'Unbranded',
    features: ['Plastic cover'],
    condition: 'Brand new',
  },
  {
    name: 'Indoor Plant Pot Set Ceramic',
    price: 18.0,
    originalPrice: null,
    images: [
      `${D}/home-decoration/plant-pot/1.webp`,
      `${D}/home-decoration/plant-pot/2.webp`,
      `${D}/home-decoration/plant-pot/3.webp`,
    ],
    description: 'Set of 3 minimalist ceramic plant pots in assorted sizes, perfect for succulents and small plants.',
    category: 'Home & Garden',
    stock: 42,
    rating: 4.2,
    reviewCount: 34,
    isFeatured: false,
    tags: ['plant', 'pot', 'ceramic', 'indoor'],
    brand: 'Unbranded',
    features: [],
    condition: 'Brand new',
  },
  {
    name: 'Digital Microwave Oven 20L',
    price: 150.0,
    originalPrice: 199.0,
    images: [
      `${D}/kitchen-accessories/microwave-oven/1.webp`,
      `${D}/kitchen-accessories/microwave-oven/2.webp`,
    ],
    description: 'Powerful digital microwave with 20L capacity, multiple power levels, and quick-defrost technology.',
    category: 'Home & Garden',
    stock: 10,
    rating: 4.6,
    reviewCount: 156,
    isFeatured: true,
    tags: ['kitchen', 'microwave', 'oven', 'appliance'],
    brand: 'Samsung',
    features: ['Energy Efficient', 'Compact Design'],
    condition: 'Brand new',
  },
  {
    name: 'Memory Foam Pillow Premium',
    price: 35.0,
    originalPrice: 45.0,
    images: [
      `${D}/home-decoration/decoration-swing/1.webp`,
    ],
    description: 'Ergonomic memory foam pillow for neck support. Breathable and hypoallergenic cover included.',
    category: 'Home & Garden',
    stock: 60,
    rating: 4.1,
    reviewCount: 88,
    isFeatured: false,
    tags: ['pillow', 'memory foam', 'sleep', 'ergonomic'],
    brand: 'Unbranded',
    features: [],
    condition: 'Refurbished',
  },
  {
    name: 'Stainless Steel Kitchen Knife Set',
    price: 65.0,
    originalPrice: null,
    images: [
      `${D}/kitchen-accessories/knife/1.webp`,
    ],
    description: 'Professional 6-piece stainless steel knife set with wooden block. Razor-sharp blades.',
    category: 'Home & Garden',
    stock: 18,
    rating: 4.4,
    reviewCount: 112,
    isFeatured: false,
    tags: ['knife', 'kitchen', 'stainless steel', 'cooking'],
    brand: 'Unbranded',
    features: ['Metallic'],
    condition: 'Brand new',
  },

  // ===== SPORTS & OUTDOOR (4) =====
  {
    name: 'Nike Running Shoes Ultra Boost',
    price: 120.0,
    originalPrice: 160.0,
    images: [
      `${D}/mens-shoes/nike-air-jordan-1-red-and-black/1.webp`,
      `${D}/mens-shoes/nike-air-jordan-1-red-and-black/2.webp`,
      `${D}/mens-shoes/nike-air-jordan-1-red-and-black/3.webp`,
    ],
    description: 'Lightweight running shoes with responsive cushioning and breathable mesh upper for maximum comfort.',
    category: 'Sports & Outdoor',
    stock: 25,
    rating: 4.8,
    reviewCount: 245,
    isFeatured: true,
    tags: ['nike', 'running', 'shoes', 'fitness'],
    brand: 'Nike',
    features: [],
    condition: 'Brand new',
  },
  {
    name: 'Professional Golf Ball Set',
    price: 25.0,
    originalPrice: null,
    images: [
      `${D}/sports-accessories/golf-ball/1.webp`,
    ],
    description: 'High-performance golf balls with aerodynamic dimple pattern for maximum distance and control.',
    category: 'Sports & Outdoor',
    stock: 50,
    rating: 4.3,
    reviewCount: 56,
    isFeatured: false,
    tags: ['golf', 'ball', 'sports', 'equipment'],
    brand: 'Unbranded',
    features: [],
    condition: 'Brand new',
  },
  {
    name: 'Mountain Bike Helmet Safety Certified',
    price: 42.0,
    originalPrice: null,
    images: [
      `${D}/sports-accessories/cricket-helmet/1.webp`,
      `${D}/sports-accessories/cricket-helmet/2.webp`,
    ],
    description: 'Lightweight mountain bike helmet with adjustable fit system and ventilation channels.',
    category: 'Sports & Outdoor',
    stock: 28,
    rating: 4.0,
    reviewCount: 33,
    isFeatured: false,
    tags: ['helmet', 'bike', 'safety', 'cycling'],
    brand: 'Unbranded',
    features: ['Plastic cover'],
    condition: 'Brand new',
  },
  {
    name: 'Leather Baseball Glove',
    price: 45.0,
    originalPrice: 60.0,
    images: [
      `${D}/sports-accessories/baseball-glove/1.webp`,
      `${D}/sports-accessories/baseball-glove/2.webp`,
    ],
    description: 'Premium leather baseball glove with deep pocket and comfortable lining for elite performance.',
    category: 'Sports & Outdoor',
    stock: 14,
    rating: 3.9,
    reviewCount: 21,
    isFeatured: false,
    tags: ['baseball', 'glove', 'sports', 'leather'],
    brand: 'Unbranded',
    features: [],
    condition: 'Brand new',
  },

  // ===== BEAUTY & HEALTH (4) =====
  {
    name: 'Face Moisturizer Hydrating Cream',
    price: 22.0,
    originalPrice: null,
    images: [
      `${D}/skin-care/vaseline-men-body-and-face-lotion/1.webp`,
      `${D}/skin-care/vaseline-men-body-and-face-lotion/2.webp`,
    ],
    description: 'Daily hydrating face cream with hyaluronic acid and vitamin E for all skin types.',
    category: 'Beauty & Health',
    stock: 70,
    rating: 4.6,
    reviewCount: 134,
    isFeatured: false,
    tags: ['moisturizer', 'skincare', 'hydrating', 'face'],
    brand: 'Unbranded',
    features: [],
    condition: 'Brand new',
  },
  {
    name: 'Pocco Electric Toothbrush Sonic Pro',
    price: 55.0,
    originalPrice: 75.0,
    images: [
      `${D}/skin-care/olay-ultra-moisture-shea-butter-body-wash/1.webp`,
    ],
    description: 'Sonic electric toothbrush with 5 cleaning modes, smart timer, and 30-day battery life.',
    category: 'Beauty & Health',
    stock: 38,
    rating: 4.4,
    reviewCount: 89,
    isFeatured: false,
    tags: ['toothbrush', 'electric', 'sonic', 'dental'],
    brand: 'Pocco',
    features: ['Super power', 'Plastic cover'],
    condition: 'Brand new',
  },
  {
    name: 'Hair Dryer Professional 2000W',
    price: 65.0,
    originalPrice: 85.0,
    images: [
      `${D}/beauty/powder-canister/1.webp`,
    ],
    description: 'Professional ionic hair dryer with 2000W power, 3 heat settings, and concentrator nozzle.',
    category: 'Beauty & Health',
    stock: 22,
    rating: 4.2,
    reviewCount: 56,
    isFeatured: false,
    tags: ['hair', 'dryer', 'professional', 'ionic'],
    brand: 'Unbranded',
    features: ['Super power'],
    condition: 'Refurbished',
  },
  {
    name: 'Massage Gun Deep Tissue Pro',
    price: 129.0,
    originalPrice: 179.0,
    images: [
      `${D}/beauty/red-lipstick/1.webp`,
    ],
    description: 'Professional deep tissue massage gun with 6 speed levels, 4 head attachments, and quiet motor.',
    category: 'Beauty & Health',
    stock: 16,
    rating: 4.5,
    reviewCount: 178,
    isFeatured: true,
    tags: ['massage', 'recovery', 'muscle', 'therapy'],
    brand: 'Unbranded',
    features: ['Super power', 'Metallic'],
    condition: 'Brand new',
  },
];

const seedDB = async () => {
  try {
    await connectDB();

    await Product.deleteMany({});
    console.log('Cleared existing products.');

    const inserted = await Product.insertMany(seedProducts);
    console.log(`Seeding complete. ${inserted.length} products inserted.`);

    const categories = [...new Set(inserted.map(p => p.category))];
    const brands = [...new Set(inserted.map(p => p.brand))];
    const featured = inserted.filter(p => p.isFeatured).length;
    console.log(`Categories (${categories.length}): ${categories.join(', ')}`);
    console.log(`Brands (${brands.length}): ${brands.join(', ')}`);
    console.log(`Featured: ${featured}`);

    await mongoose.connection.close();
    console.log('Database connection closed.');
    process.exit(0);
  } catch (error) {
    console.error(`Seeding error: ${error.message}`);
    process.exit(1);
  }
};

seedDB();
